name: Release

on:
  push:
    branches: [main]

permissions:
  contents: write
  packages: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: -D warnings

jobs:
  release:
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2

      - name: Add Rust targets
        run: >-
          rustup target add
          aarch64-apple-ios
          aarch64-apple-ios-sim
          aarch64-linux-android
          armv7-linux-androideabi
          x86_64-linux-android
          i686-linux-android

      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-ndk

      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm
          registry-url: https://npm.pkg.github.com
          scope: "@sindrip"

      - run: npm ci

      - name: Create Release Pull Request or Publish
        uses: changesets/action@v1
        with:
          version: npm run version-packages
          publish: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
